package Environment;

public enum CellType {
    FLOOR, WALL, DOOR, ENTRANCE,
    REGION_1, REGION_2, REGION_3,
    SHOP_0, SHOP_1, SHOP_2, SHOP_3, SHOP_4, SHOP_5,
    SHOP_0_CENTER, SHOP_1_CENTER, SHOP_2_CENTER, SHOP_3_CENTER, SHOP_4_CENTER, SHOP_5_CENTER
}

